export const workoutData = [
    {
      id: '1',
      name: 'Pushups',
      description: 'Pushups are a versatile bodyweight exercise that strengthens the chest, shoulders, and arms.',
      image: require('./assets/pushup.png'),
      category: 'Chest',
      recommendations: {
        Beginner: { reps: '8-10', time: '30 secs' },
        Intermediate: { reps: '15-20', time: '45 secs' },
        Advanced: { reps: '25+', time: '60 secs' },
      },
    },
    {
      id: '2',
      name: 'Sit-ups',
      description: 'Sit-ups are a classic core exercise that targets the abdominal muscles, helping to strengthen the core and improve overall stability.',
      image: require('./assets/situps.png'),
      category: 'Core',
      recommendations: {
        Beginner: { reps: '10-15', time: '30 secs' },
        Intermediate: { reps: '20-25', time: '45 secs' },
        Advanced: { reps: '30+', time: '60 secs' },
      },
    },
    {
      id: '3',
      name: 'Squats',
      description: 'Squats are a fundamental lower body exercise that targets the quadriceps, hamstrings, and glutes, helping to improve leg strength and functional movement.',
      image: require('./assets/squats.png'),
      category: 'Legs',
      recommendations: {
        Beginner: { reps: '8-10', time: '30 secs' },
        Intermediate: { reps: '15-20', time: '45 secs' },
        Advanced: { reps: '25+', time: '60 secs' },
      },
    },
    {
      id: '4',
      name: 'Lunges',
      description: 'Lunges are effective for targeting the quadriceps, hamstrings, and glutes, as well as improving balance and stability.',
      image: require('./assets/lunges.png'),
      category: 'Legs',
      recommendations: {
        Beginner: { reps: '8-10 per leg', time: '30 secs' },
        Intermediate: { reps: '15-20 per leg', time: '45 secs' },
        Advanced: { reps: '25+ per leg', time: '60 secs' },
      },
    },
    {
      id: '5',
      name: 'Planks',
      description: 'Planks are an isometric core exercise that targets the abdominal muscles, lower back, and shoulders, helping to improve core strength and stability.',
      image: require('./assets/plank.png'),
      category: 'Core',
      recommendations: {
        Beginner: { reps: 'N/A', time: '20 secs' },
        Intermediate: { reps: 'N/A', time: '40 secs' },
        Advanced: { reps: 'N/A', time: '60 secs' },
      },
    },
    {
      id: '6',
      name: 'Mountain Climbers',
      description: 'Mountain climbers are a dynamic exercise that targets the core, shoulders, and legs, while also providing cardiovascular benefits.',
      image: require('./assets/mountain.png'),
      category: 'Core',
      recommendations: {
        Beginner: { reps: 'N/A', time: '20 secs' },
        Intermediate: { reps: 'N/A', time: '40 secs' },
        Advanced: { reps: 'N/A', time: '60 secs' },
      },
    },
    {
      id: '7',
      name: 'Burpees',
      description: 'Burpees are a full-body exercise that combines elements of strength training and cardio, targeting multiple muscle groups including the chest, arms, shoulders, core, and legs.',
      image: require('./assets/burpees.png'),
      category: 'Full body',
      recommendations: {
        Beginner: { reps: '5-8', time: '30 secs' },
        Intermediate: { reps: '10-15', time: '45 secs' },
        Advanced: { reps: '20+', time: '60 secs' },
      },
    },
    {
      id: '8',
      name: 'Leg Raises',
      description: 'Leg raises are an effective abdominal exercise that targets the lower abs, helping to strengthen the core and improve hip flexibility.',
      image: require('./assets/Leg-raises.png'),
      category: 'Core',
      recommendations: {
        Beginner: { reps: '8-10', time: '30 secs' },
        Intermediate: { reps: '15-20', time: '45 secs' },
        Advanced: { reps: '25+', time: '60 secs' },
      },
    },
    {
        id: '9',
        name: 'Tricep Dips',
        description: 'Tricep dips are a bodyweight exercise that targets the triceps, shoulders, and chest, helping to improve arm strength and muscle tone.',
        image: require('./assets/dips.png'),
        category: 'Arms',
        recommendations: {
          Beginner: { reps: '8-10', time: '30 secs' },
          Intermediate: { reps: '15-20', time: '45 secs' },
          Advanced: { reps: '25+', time: '60 secs' },
        },
      },
      {
        id: '10',
        name: 'Bridge',
        description: 'Bridges are a great exercise for targeting the glutes, hamstrings, and lower back, helping to improve hip mobility and strengthen the posterior chain.',
        image: require('./assets/bridge.png'),
        category: 'Legs',
        recommendations: {
          Beginner: { reps: '10-12', time: '30 secs' },
          Intermediate: { reps: '15-20', time: '45 secs' },
          Advanced: { reps: '25+', time: '60 secs' },
        },
      },
    ];